### ISSUE TITLE
Error while updating property 'markers' of a view managed by:RCTBaiduMapview 这个是什么原因导致的

### ISSUE THREAD

**Issue by luoyechen** [SamuelZhou80/React-Native-BaiduMap-YX#4]
为什么填上photoId、imgpath，会出现闪退

**Comment by SamuelZhou80** [comment]
我估计是因为文件保存的目标路径没有创建导致的。
private static final String cachePath = SDCARD_DIR + "/rncrm/headicon/";
我这边的项目是在JS端有检查并创建路径的接口了。

**Comment by SamuelZhou80** [comment]
@luoyechen 我把代码提交了，试试看
